# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/andrew/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake

# The command to remove a file.
RM = /home/andrew/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andrew/Documents/My_Projects/cloudkey-oled-statusd

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andrew/Documents/My_Projects/cloudkey-oled-statusd

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/andrew/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/andrew/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/andrew/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/andrew/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/andrew/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/andrew/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/andrew/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/andrew/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrew/Documents/My_Projects/cloudkey-oled-statusd/CMakeFiles /home/andrew/Documents/My_Projects/cloudkey-oled-statusd//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrew/Documents/My_Projects/cloudkey-oled-statusd/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fb

# Build rule for target.
fb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fb
.PHONY : fb

# fast build rule for target.
fb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fb.dir/build.make CMakeFiles/fb.dir/build
.PHONY : fb/fast

#=============================================================================
# Target rules for targets named ui

# Build rule for target.
ui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ui
.PHONY : ui

# fast build rule for target.
ui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/build
.PHONY : ui/fast

#=============================================================================
# Target rules for targets named oled-statusd

# Build rule for target.
oled-statusd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 oled-statusd
.PHONY : oled-statusd

# fast build rule for target.
oled-statusd/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oled-statusd.dir/build.make CMakeFiles/oled-statusd.dir/build
.PHONY : oled-statusd/fast

#=============================================================================
# Target rules for targets named stats

# Build rule for target.
stats: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stats
.PHONY : stats

# fast build rule for target.
stats/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stats.dir/build.make CMakeFiles/stats.dir/build
.PHONY : stats/fast

core/led/led_controller.o: core/led/led_controller.c.o
.PHONY : core/led/led_controller.o

# target to build an object file
core/led/led_controller.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oled-statusd.dir/build.make CMakeFiles/oled-statusd.dir/core/led/led_controller.c.o
.PHONY : core/led/led_controller.c.o

core/led/led_controller.i: core/led/led_controller.c.i
.PHONY : core/led/led_controller.i

# target to preprocess a source file
core/led/led_controller.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oled-statusd.dir/build.make CMakeFiles/oled-statusd.dir/core/led/led_controller.c.i
.PHONY : core/led/led_controller.c.i

core/led/led_controller.s: core/led/led_controller.c.s
.PHONY : core/led/led_controller.s

# target to generate assembly for a file
core/led/led_controller.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oled-statusd.dir/build.make CMakeFiles/oled-statusd.dir/core/led/led_controller.c.s
.PHONY : core/led/led_controller.c.s

core/state/libre_config.o: core/state/libre_config.c.o
.PHONY : core/state/libre_config.o

# target to build an object file
core/state/libre_config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oled-statusd.dir/build.make CMakeFiles/oled-statusd.dir/core/state/libre_config.c.o
.PHONY : core/state/libre_config.c.o

core/state/libre_config.i: core/state/libre_config.c.i
.PHONY : core/state/libre_config.i

# target to preprocess a source file
core/state/libre_config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oled-statusd.dir/build.make CMakeFiles/oled-statusd.dir/core/state/libre_config.c.i
.PHONY : core/state/libre_config.c.i

core/state/libre_config.s: core/state/libre_config.c.s
.PHONY : core/state/libre_config.s

# target to generate assembly for a file
core/state/libre_config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oled-statusd.dir/build.make CMakeFiles/oled-statusd.dir/core/state/libre_config.c.s
.PHONY : core/state/libre_config.c.s

core/state/state.o: core/state/state.c.o
.PHONY : core/state/state.o

# target to build an object file
core/state/state.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oled-statusd.dir/build.make CMakeFiles/oled-statusd.dir/core/state/state.c.o
.PHONY : core/state/state.c.o

core/state/state.i: core/state/state.c.i
.PHONY : core/state/state.i

# target to preprocess a source file
core/state/state.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oled-statusd.dir/build.make CMakeFiles/oled-statusd.dir/core/state/state.c.i
.PHONY : core/state/state.c.i

core/state/state.s: core/state/state.c.s
.PHONY : core/state/state.s

# target to generate assembly for a file
core/state/state.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oled-statusd.dir/build.make CMakeFiles/oled-statusd.dir/core/state/state.c.s
.PHONY : core/state/state.c.s

fb/bitmap.o: fb/bitmap.c.o
.PHONY : fb/bitmap.o

# target to build an object file
fb/bitmap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fb.dir/build.make CMakeFiles/fb.dir/fb/bitmap.c.o
.PHONY : fb/bitmap.c.o

fb/bitmap.i: fb/bitmap.c.i
.PHONY : fb/bitmap.i

# target to preprocess a source file
fb/bitmap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fb.dir/build.make CMakeFiles/fb.dir/fb/bitmap.c.i
.PHONY : fb/bitmap.c.i

fb/bitmap.s: fb/bitmap.c.s
.PHONY : fb/bitmap.s

# target to generate assembly for a file
fb/bitmap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fb.dir/build.make CMakeFiles/fb.dir/fb/bitmap.c.s
.PHONY : fb/bitmap.c.s

fb/bitmap_loader.o: fb/bitmap_loader.c.o
.PHONY : fb/bitmap_loader.o

# target to build an object file
fb/bitmap_loader.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fb.dir/build.make CMakeFiles/fb.dir/fb/bitmap_loader.c.o
.PHONY : fb/bitmap_loader.c.o

fb/bitmap_loader.i: fb/bitmap_loader.c.i
.PHONY : fb/bitmap_loader.i

# target to preprocess a source file
fb/bitmap_loader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fb.dir/build.make CMakeFiles/fb.dir/fb/bitmap_loader.c.i
.PHONY : fb/bitmap_loader.c.i

fb/bitmap_loader.s: fb/bitmap_loader.c.s
.PHONY : fb/bitmap_loader.s

# target to generate assembly for a file
fb/bitmap_loader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fb.dir/build.make CMakeFiles/fb.dir/fb/bitmap_loader.c.s
.PHONY : fb/bitmap_loader.c.s

fb/draw.o: fb/draw.c.o
.PHONY : fb/draw.o

# target to build an object file
fb/draw.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fb.dir/build.make CMakeFiles/fb.dir/fb/draw.c.o
.PHONY : fb/draw.c.o

fb/draw.i: fb/draw.c.i
.PHONY : fb/draw.i

# target to preprocess a source file
fb/draw.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fb.dir/build.make CMakeFiles/fb.dir/fb/draw.c.i
.PHONY : fb/draw.c.i

fb/draw.s: fb/draw.c.s
.PHONY : fb/draw.s

# target to generate assembly for a file
fb/draw.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fb.dir/build.make CMakeFiles/fb.dir/fb/draw.c.s
.PHONY : fb/draw.c.s

fb/fb.o: fb/fb.c.o
.PHONY : fb/fb.o

# target to build an object file
fb/fb.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fb.dir/build.make CMakeFiles/fb.dir/fb/fb.c.o
.PHONY : fb/fb.c.o

fb/fb.i: fb/fb.c.i
.PHONY : fb/fb.i

# target to preprocess a source file
fb/fb.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fb.dir/build.make CMakeFiles/fb.dir/fb/fb.c.i
.PHONY : fb/fb.c.i

fb/fb.s: fb/fb.c.s
.PHONY : fb/fb.s

# target to generate assembly for a file
fb/fb.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fb.dir/build.make CMakeFiles/fb.dir/fb/fb.c.s
.PHONY : fb/fb.c.s

fb/text.o: fb/text.c.o
.PHONY : fb/text.o

# target to build an object file
fb/text.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fb.dir/build.make CMakeFiles/fb.dir/fb/text.c.o
.PHONY : fb/text.c.o

fb/text.i: fb/text.c.i
.PHONY : fb/text.i

# target to preprocess a source file
fb/text.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fb.dir/build.make CMakeFiles/fb.dir/fb/text.c.i
.PHONY : fb/text.c.i

fb/text.s: fb/text.c.s
.PHONY : fb/text.s

# target to generate assembly for a file
fb/text.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fb.dir/build.make CMakeFiles/fb.dir/fb/text.c.s
.PHONY : fb/text.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oled-statusd.dir/build.make CMakeFiles/oled-statusd.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oled-statusd.dir/build.make CMakeFiles/oled-statusd.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/oled-statusd.dir/build.make CMakeFiles/oled-statusd.dir/main.c.s
.PHONY : main.c.s

stats/host.o: stats/host.c.o
.PHONY : stats/host.o

# target to build an object file
stats/host.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stats.dir/build.make CMakeFiles/stats.dir/stats/host.c.o
.PHONY : stats/host.c.o

stats/host.i: stats/host.c.i
.PHONY : stats/host.i

# target to preprocess a source file
stats/host.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stats.dir/build.make CMakeFiles/stats.dir/stats/host.c.i
.PHONY : stats/host.c.i

stats/host.s: stats/host.c.s
.PHONY : stats/host.s

# target to generate assembly for a file
stats/host.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stats.dir/build.make CMakeFiles/stats.dir/stats/host.c.s
.PHONY : stats/host.c.s

stats/ip.o: stats/ip.c.o
.PHONY : stats/ip.o

# target to build an object file
stats/ip.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stats.dir/build.make CMakeFiles/stats.dir/stats/ip.c.o
.PHONY : stats/ip.c.o

stats/ip.i: stats/ip.c.i
.PHONY : stats/ip.i

# target to preprocess a source file
stats/ip.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stats.dir/build.make CMakeFiles/stats.dir/stats/ip.c.i
.PHONY : stats/ip.c.i

stats/ip.s: stats/ip.c.s
.PHONY : stats/ip.s

# target to generate assembly for a file
stats/ip.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stats.dir/build.make CMakeFiles/stats.dir/stats/ip.c.s
.PHONY : stats/ip.c.s

stats/network.o: stats/network.c.o
.PHONY : stats/network.o

# target to build an object file
stats/network.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stats.dir/build.make CMakeFiles/stats.dir/stats/network.c.o
.PHONY : stats/network.c.o

stats/network.i: stats/network.c.i
.PHONY : stats/network.i

# target to preprocess a source file
stats/network.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stats.dir/build.make CMakeFiles/stats.dir/stats/network.c.i
.PHONY : stats/network.c.i

stats/network.s: stats/network.c.s
.PHONY : stats/network.s

# target to generate assembly for a file
stats/network.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stats.dir/build.make CMakeFiles/stats.dir/stats/network.c.s
.PHONY : stats/network.c.s

stats/state.o: stats/state.c.o
.PHONY : stats/state.o

# target to build an object file
stats/state.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stats.dir/build.make CMakeFiles/stats.dir/stats/state.c.o
.PHONY : stats/state.c.o

stats/state.i: stats/state.c.i
.PHONY : stats/state.i

# target to preprocess a source file
stats/state.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stats.dir/build.make CMakeFiles/stats.dir/stats/state.c.i
.PHONY : stats/state.c.i

stats/state.s: stats/state.c.s
.PHONY : stats/state.s

# target to generate assembly for a file
stats/state.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stats.dir/build.make CMakeFiles/stats.dir/stats/state.c.s
.PHONY : stats/state.c.s

stats/system.o: stats/system.c.o
.PHONY : stats/system.o

# target to build an object file
stats/system.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stats.dir/build.make CMakeFiles/stats.dir/stats/system.c.o
.PHONY : stats/system.c.o

stats/system.i: stats/system.c.i
.PHONY : stats/system.i

# target to preprocess a source file
stats/system.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stats.dir/build.make CMakeFiles/stats.dir/stats/system.c.i
.PHONY : stats/system.c.i

stats/system.s: stats/system.c.s
.PHONY : stats/system.s

# target to generate assembly for a file
stats/system.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stats.dir/build.make CMakeFiles/stats.dir/stats/system.c.s
.PHONY : stats/system.c.s

ui/render_network.o: ui/render_network.c.o
.PHONY : ui/render_network.o

# target to build an object file
ui/render_network.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/render_network.c.o
.PHONY : ui/render_network.c.o

ui/render_network.i: ui/render_network.c.i
.PHONY : ui/render_network.i

# target to preprocess a source file
ui/render_network.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/render_network.c.i
.PHONY : ui/render_network.c.i

ui/render_network.s: ui/render_network.c.s
.PHONY : ui/render_network.s

# target to generate assembly for a file
ui/render_network.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/render_network.c.s
.PHONY : ui/render_network.c.s

ui/render_state.o: ui/render_state.c.o
.PHONY : ui/render_state.o

# target to build an object file
ui/render_state.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/render_state.c.o
.PHONY : ui/render_state.c.o

ui/render_state.i: ui/render_state.c.i
.PHONY : ui/render_state.i

# target to preprocess a source file
ui/render_state.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/render_state.c.i
.PHONY : ui/render_state.c.i

ui/render_state.s: ui/render_state.c.s
.PHONY : ui/render_state.s

# target to generate assembly for a file
ui/render_state.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/render_state.c.s
.PHONY : ui/render_state.c.s

ui/screens/identity.o: ui/screens/identity.c.o
.PHONY : ui/screens/identity.o

# target to build an object file
ui/screens/identity.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/screens/identity.c.o
.PHONY : ui/screens/identity.c.o

ui/screens/identity.i: ui/screens/identity.c.i
.PHONY : ui/screens/identity.i

# target to preprocess a source file
ui/screens/identity.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/screens/identity.c.i
.PHONY : ui/screens/identity.c.i

ui/screens/identity.s: ui/screens/identity.c.s
.PHONY : ui/screens/identity.s

# target to generate assembly for a file
ui/screens/identity.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/screens/identity.c.s
.PHONY : ui/screens/identity.c.s

ui/screens/internet.o: ui/screens/internet.c.o
.PHONY : ui/screens/internet.o

# target to build an object file
ui/screens/internet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/screens/internet.c.o
.PHONY : ui/screens/internet.c.o

ui/screens/internet.i: ui/screens/internet.c.i
.PHONY : ui/screens/internet.i

# target to preprocess a source file
ui/screens/internet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/screens/internet.c.i
.PHONY : ui/screens/internet.c.i

ui/screens/internet.s: ui/screens/internet.c.s
.PHONY : ui/screens/internet.s

# target to generate assembly for a file
ui/screens/internet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/screens/internet.c.s
.PHONY : ui/screens/internet.c.s

ui/screens/libre.o: ui/screens/libre.c.o
.PHONY : ui/screens/libre.o

# target to build an object file
ui/screens/libre.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/screens/libre.c.o
.PHONY : ui/screens/libre.c.o

ui/screens/libre.i: ui/screens/libre.c.i
.PHONY : ui/screens/libre.i

# target to preprocess a source file
ui/screens/libre.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/screens/libre.c.i
.PHONY : ui/screens/libre.c.i

ui/screens/libre.s: ui/screens/libre.c.s
.PHONY : ui/screens/libre.s

# target to generate assembly for a file
ui/screens/libre.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/screens/libre.c.s
.PHONY : ui/screens/libre.c.s

ui/screens/splash.o: ui/screens/splash.c.o
.PHONY : ui/screens/splash.o

# target to build an object file
ui/screens/splash.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/screens/splash.c.o
.PHONY : ui/screens/splash.c.o

ui/screens/splash.i: ui/screens/splash.c.i
.PHONY : ui/screens/splash.i

# target to preprocess a source file
ui/screens/splash.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/screens/splash.c.i
.PHONY : ui/screens/splash.c.i

ui/screens/splash.s: ui/screens/splash.c.s
.PHONY : ui/screens/splash.s

# target to generate assembly for a file
ui/screens/splash.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/screens/splash.c.s
.PHONY : ui/screens/splash.c.s

ui/screens/system_health.o: ui/screens/system_health.c.o
.PHONY : ui/screens/system_health.o

# target to build an object file
ui/screens/system_health.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/screens/system_health.c.o
.PHONY : ui/screens/system_health.c.o

ui/screens/system_health.i: ui/screens/system_health.c.i
.PHONY : ui/screens/system_health.i

# target to preprocess a source file
ui/screens/system_health.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/screens/system_health.c.i
.PHONY : ui/screens/system_health.c.i

ui/screens/system_health.s: ui/screens/system_health.c.s
.PHONY : ui/screens/system_health.s

# target to generate assembly for a file
ui/screens/system_health.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/screens/system_health.c.s
.PHONY : ui/screens/system_health.c.s

ui/screens/uptime.o: ui/screens/uptime.c.o
.PHONY : ui/screens/uptime.o

# target to build an object file
ui/screens/uptime.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/screens/uptime.c.o
.PHONY : ui/screens/uptime.c.o

ui/screens/uptime.i: ui/screens/uptime.c.i
.PHONY : ui/screens/uptime.i

# target to preprocess a source file
ui/screens/uptime.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/screens/uptime.c.i
.PHONY : ui/screens/uptime.c.i

ui/screens/uptime.s: ui/screens/uptime.c.s
.PHONY : ui/screens/uptime.s

# target to generate assembly for a file
ui/screens/uptime.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/screens/uptime.c.s
.PHONY : ui/screens/uptime.c.s

ui/state_icons.o: ui/state_icons.c.o
.PHONY : ui/state_icons.o

# target to build an object file
ui/state_icons.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/state_icons.c.o
.PHONY : ui/state_icons.c.o

ui/state_icons.i: ui/state_icons.c.i
.PHONY : ui/state_icons.i

# target to preprocess a source file
ui/state_icons.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/state_icons.c.i
.PHONY : ui/state_icons.c.i

ui/state_icons.s: ui/state_icons.c.s
.PHONY : ui/state_icons.s

# target to generate assembly for a file
ui/state_icons.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/state_icons.c.s
.PHONY : ui/state_icons.c.s

ui/ui_manager.o: ui/ui_manager.c.o
.PHONY : ui/ui_manager.o

# target to build an object file
ui/ui_manager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/ui_manager.c.o
.PHONY : ui/ui_manager.c.o

ui/ui_manager.i: ui/ui_manager.c.i
.PHONY : ui/ui_manager.i

# target to preprocess a source file
ui/ui_manager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/ui_manager.c.i
.PHONY : ui/ui_manager.c.i

ui/ui_manager.s: ui/ui_manager.c.s
.PHONY : ui/ui_manager.s

# target to generate assembly for a file
ui/ui_manager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ui.dir/build.make CMakeFiles/ui.dir/ui/ui_manager.c.s
.PHONY : ui/ui_manager.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... fb"
	@echo "... oled-statusd"
	@echo "... stats"
	@echo "... ui"
	@echo "... core/led/led_controller.o"
	@echo "... core/led/led_controller.i"
	@echo "... core/led/led_controller.s"
	@echo "... core/state/libre_config.o"
	@echo "... core/state/libre_config.i"
	@echo "... core/state/libre_config.s"
	@echo "... core/state/state.o"
	@echo "... core/state/state.i"
	@echo "... core/state/state.s"
	@echo "... fb/bitmap.o"
	@echo "... fb/bitmap.i"
	@echo "... fb/bitmap.s"
	@echo "... fb/bitmap_loader.o"
	@echo "... fb/bitmap_loader.i"
	@echo "... fb/bitmap_loader.s"
	@echo "... fb/draw.o"
	@echo "... fb/draw.i"
	@echo "... fb/draw.s"
	@echo "... fb/fb.o"
	@echo "... fb/fb.i"
	@echo "... fb/fb.s"
	@echo "... fb/text.o"
	@echo "... fb/text.i"
	@echo "... fb/text.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... stats/host.o"
	@echo "... stats/host.i"
	@echo "... stats/host.s"
	@echo "... stats/ip.o"
	@echo "... stats/ip.i"
	@echo "... stats/ip.s"
	@echo "... stats/network.o"
	@echo "... stats/network.i"
	@echo "... stats/network.s"
	@echo "... stats/state.o"
	@echo "... stats/state.i"
	@echo "... stats/state.s"
	@echo "... stats/system.o"
	@echo "... stats/system.i"
	@echo "... stats/system.s"
	@echo "... ui/render_network.o"
	@echo "... ui/render_network.i"
	@echo "... ui/render_network.s"
	@echo "... ui/render_state.o"
	@echo "... ui/render_state.i"
	@echo "... ui/render_state.s"
	@echo "... ui/screens/identity.o"
	@echo "... ui/screens/identity.i"
	@echo "... ui/screens/identity.s"
	@echo "... ui/screens/internet.o"
	@echo "... ui/screens/internet.i"
	@echo "... ui/screens/internet.s"
	@echo "... ui/screens/libre.o"
	@echo "... ui/screens/libre.i"
	@echo "... ui/screens/libre.s"
	@echo "... ui/screens/splash.o"
	@echo "... ui/screens/splash.i"
	@echo "... ui/screens/splash.s"
	@echo "... ui/screens/system_health.o"
	@echo "... ui/screens/system_health.i"
	@echo "... ui/screens/system_health.s"
	@echo "... ui/screens/uptime.o"
	@echo "... ui/screens/uptime.i"
	@echo "... ui/screens/uptime.s"
	@echo "... ui/state_icons.o"
	@echo "... ui/state_icons.i"
	@echo "... ui/state_icons.s"
	@echo "... ui/ui_manager.o"
	@echo "... ui/ui_manager.i"
	@echo "... ui/ui_manager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

